server:
  port: 8084

eureka:
  instance:
    hostname: localhost # 启动地址
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://username:password123456@${eureka.instance.hostname}:8083/eureka/
# 设置访问eureka的密码
spring:
  security:
    basic:
      enabled: true
    user:
      name: username
      password: password123456
