server:
  port: 8082

user:
  userServicePath: http://SERVICE-PROVIDER/user/    # 服务调用地址修改为 eureka 中的地址

eureka:
  client:
    service-url:
      defaultZone: http://username:password123456@localhost:8083/eureka/, http://username:password123456@localhost:8084/eureka/
spring:
  application:
    name: service-consumer  # 制定服务提供者的服务名
# 配置日志追踪级别为 debug
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG



