server:
  port: 8082

user:
  userServicePath: http://SERVICE-PROVIDER/user/    # 服务调用地址修改为 eureka 中的地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/
spring:
  application:
    name: service-consumer  # 制定服务提供者的服务名