server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://username:password123456@localhost:8083/eureka/, http://username:password123456@localhost:8084/eureka/
spring:
  application:
    name: service-provider  # 制定服务提供者的服务名
